# Copyright Joe Motacek All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  orderer:
    image: hyperledger/fabric-orderer:x86_64-1.0.4
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - CORE_VM_DOCKER_HOSTCONFIG_MEMORY=536870912
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:x86_64-1.0.4
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_CAR_RUNTIME=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_JAVA=hyperledger/fabric-javaenv:x86_64-1.0.4
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    hostname: orderer.ptunstad.no
    networks:
      hyperledger-fabric:
        aliases:
          - orderer.ptunstad.no
    volumes:
      - /data/hyperledger-pi-composer/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /data/hyperledger-pi-composer/crypto-config/ordererOrganizations/ptunstad.no/orderers/orderer.ptunstad.no/msp:/var/hyperledger/orderer/msp
      - /data/hyperledger-pi-composer/crypto-config/ordererOrganizations/ptunstad.no/orderers/orderer.ptunstad.no/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    deploy:
      placement:
        constraints:
          - node.hostname == agc-lab2
    command: orderer
    
  peer0_org1:
    image: hyperledger/fabric-peer:x86_64-1.0.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-fabric
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.ptunstad.no
      - CORE_PEER_ADDRESS=peer0.org1.ptunstad.no:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.ptunstad.no:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_DOCKER_HOSTCONFIG_MEMORY=536870912
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:x86_64-1.0.4
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_CAR_RUNTIME=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_JAVA=hyperledger/fabric-javaenv:x86_64-1.0.4
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    hostname: peer0.org1.ptunstad.no
    networks:
      hyperledger-fabric:
        aliases:
          - peer0.org1.ptunstad.no
    volumes:
      - /var/run/:/host/var/run/
      - /data/hyperledger-pi-composer/logs:/home/logs
      - /data/hyperledger-pi-composer/crypto-config/peerOrganizations/org1.ptunstad.no/peers/peer0.org1.ptunstad.no/msp:/etc/hyperledger/fabric/msp
      - /data/hyperledger-pi-composer/crypto-config/peerOrganizations/org1.ptunstad.no/peers/peer0.org1.ptunstad.no/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053
    deploy:
      placement:
        constraints:
          - node.hostname == agc-lab2
    command: bash -c "peer node start > /home/logs/peer0org1log.txt 2>&1"

  peer1_org1:
    image: hyperledger/fabric-peer:x86_64-1.0.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-fabric
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.org1.ptunstad.no
      - CORE_PEER_ADDRESS=peer1.org1.ptunstad.no:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.ptunstad.no:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.ptunstad.no:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_DOCKER_HOSTCONFIG_MEMORY=536870912
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:x86_64-1.0.4
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_CAR_RUNTIME=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_JAVA=hyperledger/fabric-javaenv:x86_64-1.0.4
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    hostname: peer1.org1.ptunstad.no
    networks:
      hyperledger-fabric:
        aliases:
          - peer1.org1.ptunstad.no
    volumes:
      - /var/run/:/host/var/run/
      - /data/hyperledger-pi-composer/logs:/home/logs
      - /data/hyperledger-pi-composer/crypto-config/peerOrganizations/org1.ptunstad.no/peers/peer1.org1.ptunstad.no/msp:/etc/hyperledger/fabric/msp
      - /data/hyperledger-pi-composer/crypto-config/peerOrganizations/org1.ptunstad.no/peers/peer1.org1.ptunstad.no/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053
    deploy:
      placement:
        constraints:
          - node.hostname == i3serv
    command: bash -c "peer node start > /home/logs/peer1org1log.txt 2>&1"

  peer2_org1:
    image: hyperledger/fabric-peer:x86_64-1.0.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-fabric
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer2.org1.ptunstad.no
      - CORE_PEER_ADDRESS=peer2.org1.ptunstad.no:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.ptunstad.no:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.org1.ptunstad.no:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_DOCKER_HOSTCONFIG_MEMORY=536870912
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:x86_64-1.0.4
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_CAR_RUNTIME=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_JAVA=hyperledger/fabric-javaenv:x86_64-1.0.4
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    hostname: peer2.org1.ptunstad.no
    networks:
      hyperledger-fabric:
        aliases:
          - peer2.org1.ptunstad.no
    volumes:
      - /var/run/:/host/var/run/
      - /data/hyperledger-pi-composer/logs:/home/logs
      - /data/hyperledger-pi-composer/crypto-config/peerOrganizations/org1.ptunstad.no/peers/peer2.org1.ptunstad.no/msp:/etc/hyperledger/fabric/msp
      - /data/hyperledger-pi-composer/crypto-config/peerOrganizations/org1.ptunstad.no/peers/peer2.org1.ptunstad.no/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053
    deploy:
      placement:
        constraints:
          - node.hostname == agc-lab1
    command: bash -c "peer node start > /home/logs/peer2org1log.txt 2>&1"

  peer3_org1:
    image: hyperledger/fabric-peer:x86_64-1.0.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-fabric
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer3.org1.ptunstad.no
      - CORE_PEER_ADDRESS=peer3.org1.ptunstad.no:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1.ptunstad.no:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.org1.ptunstad.no:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_DOCKER_HOSTCONFIG_MEMORY=536870912
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:x86_64-1.0.4
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_CAR_RUNTIME=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_JAVA=hyperledger/fabric-javaenv:x86_64-1.0.4
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    hostname: peer3.org1.ptunstad.no
    networks:
      hyperledger-fabric:
        aliases:
          - peer3.org1.ptunstad.no
    volumes:
      - /var/run/:/host/var/run/
      - /data/hyperledger-pi-composer/logs:/home/logs
      - /data/hyperledger-pi-composer/crypto-config/peerOrganizations/org1.ptunstad.no/peers/peer3.org1.ptunstad.no/msp:/etc/hyperledger/fabric/msp
      - /data/hyperledger-pi-composer/crypto-config/peerOrganizations/org1.ptunstad.no/peers/peer3.org1.ptunstad.no/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
    deploy:
      placement:
        constraints:
          - node.hostname == ptserv
    command: bash -c "peer node start > /home/logs/peer3org1log.txt 2>&1"

  cli:
    image: hyperledger/fabric-tools:x86_64-1.0.4
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.ptunstad.no:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.ptunstad.no/peers/peer0.org1.ptunstad.no/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.ptunstad.no/peers/peer0.org1.ptunstad.no/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.ptunstad.no/peers/peer0.org1.ptunstad.no/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.ptunstad.no/users/Admin@org1.ptunstad.no/msp
      - CORE_VM_DOCKER_HOSTCONFIG_MEMORY=536870912
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:x86_64-1.0.4
      - CORE_CHAINCODE_GOLANG=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_CAR=hyperledger/fabric-baseos:x86_64-0.3.2
      - CORE_CHAINCODE_JAVA=hyperledger/fabric-javaenv:x86_64-1.0.4
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'sleep 30; ./scripts/script_ds.sh; while true; do sleep 20170504; done'
    volumes:
      - /var/run/:/host/var/run/
      - /data/hyperledger-pi-composer/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
      - /data/hyperledger-pi-composer/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - /data/hyperledger-pi-composer/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - /data/hyperledger-pi-composer/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer
      - peer0_org1
      - peer1_org1
      - peer2_org1
      - peer3_org1
    deploy:
      placement:
        constraints:
          - node.hostname == agc-lab2
    networks:
      hyperledger-fabric:
        aliases:
          - cli.ptunstad.no

networks:
  hyperledger-fabric:
    external: true
